name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
     
  test:
    name: Run unit tests
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    - name: Run test
      run: go mod tidy && go test ./...

